### ISSUE TITLE
Meeting doesn't always register as ended in the database

### ISSUE THREAD

**Issue by ameliashort331** [maddalihanumateja/ParticipateInRemoteDesign#46]
If the last person in the meeting leaves the meeting in a non-traditional way (eg. simply closes the browser), the database is not updated to reflect that the meeting has ended.

**Comment by maddalihanumateja** [comment]
There should be socket code on the server side which generates an event to update the database when a user closes their bowser or logs off. Maybe the error is there? If the code is actually on the client side then it makes sense that no database update event is generated since the browser is closed.

**Comment by ameliashort331** [comment]
Sorry! This was an error I discovered a couple days ago, but forgot to add to github. I've since solved it, though. Was just in the process of uploading a [video demoing it](https://www.youtube.com/watch?v=EuPyaAAPPpo).

The latest code push checks if there are any members left in the meeting room, and then emits a "meeting ended" message if the number of members left are 0.
